questao03: questao03.c
	gcc questao03.c -o executavel.exe
	.\executavel.exe 

questao04: questao04.c
	gcc questao04.c -o executavel.exe
	.\executavel.exe

questao05: questao05.c 
	gcc questao05.c -o executavel.exe
	.\executavel.exe